config/routes.rb
Rails.application.routes.draw do
  root to: 'landings#index'
  get 'lift_index', to: 'lifts#lift_index'
  resources :landings, only: [:index, :show], as: :accueil
  resources :reponses, only: [:new, :create]
  resources :pages, only: [:index, :show], as: :pages
  resources :lifts do
    resources :passengers, only: [:index, :new, :show, :create]
  end
  resources :dress_codes, only: [:index], as: :dress_code
  resources :photos, only: [:index], as: :photos
  resources :remerciements, only: [:new, :create]
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dress_code.rb
class DressCode < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/landing.rb
class Landing < ApplicationRecord
end

app/models/lift.rb
class Lift < ApplicationRecord
  has_many :passengers, dependent: :destroy
  validates :first_name, :family_name, :places_available, :contact, :rallying_point, :departure, presence: true
  validates :places_available, inclusion: { in: 0..7 }, numericality: { only_integer: true }
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :lift
  validates :first_name, :family_name, :places, :contact, presence: true
  validates :places, inclusion: { in: 0..7 }, numericality: { only_integer: true }
  after_create :send_emails
  def send_emails
    UserMailer.with(passanger: self).lifts_passanger.deliver_now
    UserMailer.with(passanger: self).lifts_conducteur.deliver_now
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/remerciement.rb
class Remerciement < ApplicationRecord
  validates :first_name, :family_name, :message, presence: true
  after_create :send_emails
  def send_emails
    UserMailer.with(remerciements: self).remerciements.deliver_now
  end
end

app/models/reponse.rb
class Reponse < ApplicationRecord
  validates :first_name, :family_name, :contact, presence: true
  after_create :send_emails
  def send_emails
    UserMailer.with(reponse: self).confirmation_participation.deliver_now
    UserMailer.with(reponse: self).confirmation.deliver_now

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dress_codes_controller.rb
class DressCodesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all

    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude
      }
    end
  end

  def show
    # @event = Event.find(params[:id])

    @event = Event.find(params[:id])
    if @event.geocoded?
      @markers = [
                    lat: @event.latitude,
                    lng: @event.longitude,
                    infoWindow: { content: render_to_string(partial: "/landings/info_window", locals: { event: @event }) }
                  ]
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path, notice: "La localisation de l'event a bien été enregistrée."
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :address)
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
    @events = Event.all

    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: { content: render_to_string(partial: "/landings/info_window", locals: { event: event }) },
      }
    end
  end

  def show
    @event = Event.find(params[:id])
    # if @event.geocoded?
    #   @markers = [
    #                 lat: @event.latitude,
    #                 lng: @event.longitude,
    #                 infoWindow: { content: render_to_string(partial: "/landings/info_window", locals: { event: @event }) }
    #               ]
    # end
  end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  def index
    @lifts = Lift.all
  end

  def lift_index
    @lifts = Lift.all
  end

  def show
    @lift = Lift.find(params[:id])
  end

  def new
    @lift = Lift.new
  end

  def edit
    @lift = Lift.find(params[:id])
  end

  def create
    @lift = Lift.new(lift_params)
    if @lift.save
      redirect_to lifts_path, notice: "Votre trajet à bien été enregistré, merci d'avance."
    else
      render :new
    end
  end

  private

  def lift_params
    params.require(:lift).permit(:first_name, :family_name, :places_available, :contact, :rallying_point, :departure, :return)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @lifts = Lift.all
  end

  def show
    @lifts = Lift.all
    @lift = Lift.find(params[:id])
  end

  private

  def lift_params
    params.require(:lift).permit(:first_name, :family_name, :places_available, :contact,
                                 :rallying_point, :departure, :return)
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_lift

  def index
    @passengers = Passenger.all
  end

  def new
    @passenger = Passenger.new
  end

  def edit
    @passenger = Passenger.find(params[:lift_id])
  end

  def create
    @passenger = Passenger.new(passenger_params)
    @passenger.lift = @lift
    if @passenger.save
      redirect_to lifts_path, notice: "Votre trajet à bien été enregistré, vous serez mis en contact avec le Bob de votre choix."
    else
      render :new
    end
  end

  def update
    @passenger = Passenger.find(params[:lift_id])
    @passenger.update(passenger_params)
    redirect_to lifts_path
  end

  def destroy
    @passenger = Passenger.find(params[:lift_id])
    @passenger.destroy
    redirect_to lifts_path
  end

  private

  def set_lift
    @lift = Lift.find(params[:lift_id])
  end

  def passenger_params
    params.require(:passenger).permit(:first_name, :family_name, :places, :contact, :aller, :retour, :lift_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/remerciements_controller.rb
class RemerciementsController < ApplicationController
  def new
    @remerciement = Remerciement.new
  end

  def create
    @remerciement = Remerciement.new(remerciement_params)
    if @remerciement.save
      redirect_to accueil_index_path, notice: "Votre remerciement à bien été enregistré."
    else
      render :new
    end
  end

  private

  def remerciement_params
    params.require(:remerciement).permit(:first_name, :family_name, :contact, :vegetarian, :message)
  end
end

app/controllers/reponses_controller.rb
 class ReponsesController < ApplicationController
  def index
    @reponses = Reponse.all

  end
  def new
    @reponse = Reponse.new
  end

  def create
    @reponse = Reponse.new(reponse_params)
    if @reponse.save
      redirect_to accueil_index_path, notice: "Votre réponse à bien été enregistrée."
    else
      render :new
    end
  end

  private

  def reponse_params
    params.require(:reponse).permit(:first_name, :family_name, :contact, :vegetarian, :participation, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dress_codes/index.html.erb
<div class="dc-cont">
  <div class="dc-top-cont">
    <div class="dc-bg1">
      <%= cl_image_tag("ofayem9xd56rixqioqyu") %>
    </div>
    <div class="dc-intro">
      <div class="dc-title"><h1>TOUCHE - DRESS CODE</h1></div>
      <div class="dc-sub-title"><br>SHINING AMONG THE STARS</div>
    </div>
  </div>
  <div class="dc-bg2">
    <%= cl_image_tag("nrkgbrxhvbqobstcrw64") %>
  </div>
  <div class="dc-chart">
    <div class="dc-chart-title"><h2>INSPIRATIONS</h2></div>
    <div class="constellation">
      <div class="dc-pic" id="dc-pic-1">
        <%= cl_image_tag("nm9csru0mfvk26x6yrz9") %>
      </div>

      <div class="dc-pic" id="dc-pic-2">
        <%= cl_image_tag("fdpbn8xkrcpgljyxtn8g") %>
      </div>

      <div class="dc-pic" id="dc-pic-3">
        <%= cl_image_tag("pyrqcfkuayjkguk1vhn0") %>
      </div>

      <div class="dc-pic" id="dc-pic-4">
        <%= cl_image_tag("zdba3bbqlh6e33gz9xda") %>
      </div>

      <div class="dc-pic" id="dc-pic-5">
        <%= cl_image_tag("eniwv7e7uv3l2uhd1if6") %>
      </div>

      <div class="dc-pic" id="dc-pic-6">
        <%= cl_image_tag("xiwonoq4uta1ykx26fgo") %>
      </div>

      <div class="dc-pic" id="dc-pic-7">
        <%= cl_image_tag("zfcewewtrwu2q5lm7sqs") %>
      </div>

      <div class="line" id="line-1"></div>

      <div class="line" id="line-2"></div>

      <div class="line" id="line-3"></div>

      <div class="line" id="line-4"></div>

      <div class="line" id="line-5"></div>

      <div class="line" id="line-6"></div>

      <div class="line" id="line-7"></div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/events/show.html.erb
<div class="map-cont-small">

  <div class="map-small-bg">
    <%= cl_image_tag("nrkgbrxhvbqobstcrw64") %>
  </div>

  <div class="map_placer">

    <div id="map-small"
         style="width: 90vw; height: 80vh; z-index: 3; border-radius: 5px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

  </div>

</div>
<%= render 'shared/footer' %>

app/views/landings/_info_window.html.erb
<h6><strong><%= event.name %></strong>:<br><em><%= event.address.downcase.capitalize %></em></h6>

app/views/landings/index.html.erb
<div class="landing-cont">
  <div class="landing-fixed-background">
    <%= cl_image_tag("ba8gmupraokuj40knyst") %>
  </div>
  <div class="landing-scroll">
    <div class="title-cont">
      <div class="title-ban">
        <%= cl_image_tag("bsbddzrt2ebbtbgqx19e") %>
      </div>
      <div class="next-sign">
        <%= cl_image_tag("uniao8qujoldca1modjl") %>
      </div>
    </div>
    <div class="invit-cont">
      <div class="invitation-img">
        <%= cl_image_tag("nrkgbrxhvbqobstcrw64") %>
      </div>

      <div class="invit-txt-top-left">
        le Chevalier et Madame<br>Bruno de Ghellinck
      </div>

      <div class="invit-txt-top-right">
        Monsieur et Madame<br>Bruno Montens
      </div>

      <div class="invit-txt-top-centre">
        Vous prient d’assister à la soirée qu’ils donneront pour leur filles
      </div>

      <div class="invit-name-left">
        <div class="first-letter">E</div>LINE
      </div>

      <div class="invit-logo">
        <%= cl_image_tag("o4tyvisosd6ojygbs4r3") %>
      </div>

      <div class="invit-name-right">
        <div class="first-letter">A</div>STRID
      </div>

      <div class="invit-date">
        Le Samedi 15 Février 2020 à 20 heures
      </div>

      <div class="invit-bottom-left">
        Proximus Lounge
          <br>Rue Stroobants 51 - 1140 Evere
          <br>Gsm du jour: 0477 545 145
      </div>

      <div class="invit-bottom-centre">
        Diner à 21 heures précises
          <br>Black tie - Northern Lights Touch
      </div>

      <div class="invit-bottom-right">
        RSVP avant le 15 Janvier
          <!-- <br>via
          <br>www.site-de-Gauthier.be -->
      </div>

      <div class="localisation-text">
        LOCALISATION
        <br>_______________________________
        <br>
        <br>PROXIMUS LOUNGE
        <br>
        <div class="event_address_small">
          <%= link_to "#{Event.last.address.upcase}", event_path(Event.last) %>
        </div>

        <div class="event_address_big">
          <%= "#{Event.last.address.upcase}" %>
        </div>

        RALLYES B YOU & CRAZY TOGETHER
      </div>

      <div class="localisation-map">
        <div id="map"
             style="width: 42vw; height: 34vh; border-radius: 5px;"
             data-markers="<%= @markers.to_json %>"
             data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>

      <div class="invit-groups">
        Groupe1  -  Groupe2  -  Groupe3  -  Groupe4  -  Groupe5
      </div>

      <div class="response-cont">
        <div class="btn response-btn">
          <%= link_to "Répondre à l'invitation",  new_reponse_path %>
        </div>
      </div>
    </div>
    <div class="footer-land">
      Copyright © 2020 István Lázár & Gauthier Wolters <br>
      All rights reserved.
    </div>
  </div>
</div>

app/views/lifts/index.html.erb
<!--  TODO:  <div class="table-responsive"></div> -->

<div class="lift-cont">
  <div class="lift-bg">
    <%= cl_image_tag("nrkgbrxhvbqobstcrw64") %>
  </div>

  <% if @lifts.count == 0 %>
    <div class="list-cont-empty">
      <div class="lift_title_empty effect3d">
        <strong>DÉSOLÉ, NOUS N'AVONS PAS ENCORE DE SUPER-MARIOS DISPONIBLES POUR L'INSTANT..</strong>
      </div>
      <div class="empty_list">
        <%= cl_image_tag("ro9i6ihlhxur7avnvajn") %>
      </div>
      <div class="bottom-empty-btns">
        <div class="btn-lift-new">
          <%= link_to "JE PROPOSE UN LIFT!", new_lift_path %>
        </div>
        <div class="btn-lift-new">
          <%= link_to "Back", pages_path %>
        </div>
      </div>
    </div>

  <% elsif @lifts.count >= 10 %>

    <div class="list-cont-big">
      <div class="full_title_lift">
        <div class="lift_title effect3d">
          <strong>NOS SUPER-MARIOS!  🍄 🌟</strong>
        </div>
        <div class="lift_subtitle">
          <small>Tu n'as qu'à sélectionner directement celui qui te convient le mieux ;)</small>
        </div>
      </div>
      <div class="table_cont">
        <div class="lift_table">
          <div class="lists_header" id="name_header">
            <strong>NOM</strong>
          </div>

          <div class="lists_header" id="rallying_header">
            <strong>POINT DE RALLIEMENT</strong>
          </div>

          <div class="lists_header" id="departure_header">
            <strong>HEURE DE<br>DÉPART</strong>
          </div>

          <div class="lists_header" id="return_header">
            <strong>HEURE DE<br>RETOUR</strong>
          </div>

          <div class="lists_header" id="places_header">
            <strong>PLACES<br>LIBRES</strong>
          </div>

          <div class="lists_header" id="contact_header">
            <strong>CONTACT</strong>
          </div>

          <div class="lists_header" id="ticking_box_header">
            <strong>JE RÉSERVE!</strong>
          </div>
        </div>

        <% @lifts.each do |lift| %>
          <div class="lift_table">
            <div class="lists_header" id="name_header">
              <%= lift.first_name %> <%= lift.family_name %>
            </div>

            <div class="lists_header" id="rallying_header">
              <%= lift.rallying_point %>
            </div>

            <div class="lists_header" id="departure_header">
              <%= lift.departure.strftime('%H:%M') %>
            </div>

            <div class="lists_header" id="return_header">
              <% if lift.return.nil? %>
                N/A
              <% else %>
                <%= lift.return.strftime('%H:%M') %>
              <% end %>
            </div>

            <div class="lists_header" id="places_header">
              <% array = [0] %>
                <% lift.passengers.each do |passenger| %>
                  <% array << passenger.places %>
                <% end %>
              <% places_used = array.inject(0){|sum, pl| sum + pl } %>
              <%= lift.places_available - places_used %>
            </div>

            <div class="lists_header" id="contact_header">
              <%= lift.contact %>
            </div>

            <% if places_used == lift.places_available %>
              <div class="lists_header" id="ticking_box_full">
                <strong>FULL</strong>
              </div>
            <% else %>
              <div class="lists_header" id="ticking_box_valid">

                <%= link_to "GO!", new_lift_passenger_path(lift) %>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="btn-lift-new">
          <%= link_to "Back", pages_path %>
        </div>
      </div>
    </div>

  <% else %>
    <div class="list-cont">
      <div class="full_title_lift">
        <div class="lift_title effect3d">
          <strong>NOS SUPER-MARIOS!  🍄 🌟</strong>
        </div>
        <div class="lift_subtitle">
          <small>Sélectionne directement celui que tu préfères! <br> Nous vous mettrons en contact</small>
        </div>
      </div>
      <div class="table_cont">
        <div class="lift_table">
          <div class="lists_header" id="name_header">
            <strong>NOM</strong>
          </div>

          <div class="lists_header" id="rallying_header">
            <strong>POINT DE RALLIEMENT</strong>
          </div>

          <div class="lists_header" id="departure_header">
            <strong>HEURE DE<br>DÉPART</strong>
          </div>

          <div class="lists_header" id="return_header">
            <strong>HEURE DE<br>RETOUR</strong>
          </div>

          <div class="lists_header" id="places_header">
            <strong>PLACES<br>LIBRES</strong>
          </div>

          <div class="lists_header" id="contact_header">
            <strong>CONTACT</strong>
          </div>

          <div class="lists_header" id="ticking_box_header">
            <strong>JE RÉSERVE!</strong>
          </div>
        </div>

        <% @lifts.each do |lift| %>
          <div class="lift_table">
            <div class="lists_header" id="name_header">
              <%= lift.first_name %> <%= lift.family_name %>
            </div>

            <div class="lists_header" id="rallying_header">
              <%= lift.rallying_point %>
            </div>

            <div class="lists_header" id="departure_header">
              <%= lift.departure.strftime('%H:%M') %>
            </div>

            <div class="lists_header" id="return_header">
              <% if lift.return.nil? %>
                N/A
              <% else %>
                <%= lift.return.strftime('%H:%M') %>
              <% end %>
            </div>

            <div class="lists_header" id="places_header">
              <% array = [0] %>
                <% lift.passengers.each do |passenger| %>
                  <% array << passenger.places %>
                <% end %>
              <% places_used = array.inject(0){|sum, pl| sum + pl } %>
              <%= lift.places_available - places_used %>
            </div>

            <div class="lists_header" id="contact_header">
              <%= lift.contact %>
            </div>


            <% if places_used == lift.places_available %>
              <div class="lists_header" id="ticking_box_full">
                <strong>FULL</strong>
              </div>
            <% else %>
              <div class="lists_header" id="ticking_box_valid">
                <%= link_to "GO!", new_lift_passenger_path(lift) %>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="btn-lift-new">
          <%= link_to "Back", pages_path %>
        </div>
      </div>
    </div>
  <% end %>

</div>
<%= render 'shared/footer' %>

app/views/lifts/lift_index.html.erb
<div class="lift-cont">
  <div class="lift-bg">
    <%= cl_image_tag("nrkgbrxhvbqobstcrw64") %>
  </div>

  <% if @lifts.count == 0 %>
    <div class="list-cont-empty">
      <div class="lift_title_empty effect3d">
        <strong>NOUS N'AVONS PAS ENCORE DE SUPER-MARIOS, EST-TU SUR DE DÉJÀ ÊTRE UN DE NOS CHERS LIFTS..?</strong>
      </div>
      <div class="empty_list">
        <%= cl_image_tag("ro9i6ihlhxur7avnvajn") %>
      </div>
      <div class="bottom-empty-btns">
        <div class="btn-lift-new">
          <%= link_to "JE PROPOSE UN LIFT!", new_lift_path %>
        </div>
        <div class="btn-lift-new">
          <%= link_to "Back", pages_path %>
        </div>
      </div>
    </div>

  <% elsif @lifts.count >= 10 %>

    <div class="list-cont-big">
      <div class="full_title_lift">
        <div class="lift_title effect3d">
          <strong>NOS SUPER-MARIOS!  🍄 🌟</strong>
        </div>
        <div class="lift_subtitle">
          <small>Lequel de nos Super-Mario es-tu?</small>
        </div>
      </div>
      <div class="table_cont">
        <div class="lift_table">
          <div class="lists_header" id="name_header">
            <strong>NOM</strong>
          </div>

          <div class="lists_header" id="rallying_header">
            <strong>POINT DE RALLIEMENT</strong>
          </div>

          <div class="lists_header" id="departure_header">
            <strong>HEURE DE<br>DÉPART</strong>
          </div>

          <div class="lists_header" id="return_header">
            <strong>HEURE DE<br>RETOUR</strong>
          </div>

          <div class="lists_header" id="places_header">
            <strong>PLACES<br>LIBRES</strong>
          </div>

          <div class="lists_header" id="contact_header">
            <strong>CONTACT</strong>
          </div>

          <div class="lists_header" id="ticking_box_header">
            <strong>LEQUEL ES-TU?</strong>
          </div>
        </div>

        <% @lifts.each do |lift| %>
          <div class="lift_table">
            <div class="lists_header" id="name_header">
              <%= lift.first_name %> <%= lift.family_name %>
            </div>

            <div class="lists_header" id="rallying_header">
              <%= lift.rallying_point %>
            </div>

            <div class="lists_header" id="departure_header">
              <%= lift.departure.strftime('%H:%M') %>
            </div>

            <div class="lists_header" id="return_header">
              <% if lift.return.nil? %>
                N/A
              <% else %>
                <%= lift.return.strftime('%H:%M') %>
              <% end %>
            </div>

            <div class="lists_header" id="places_header">
              <% array = [0] %>
                <% lift.passengers.each do |passenger| %>
                  <% array << passenger.places %>
                <% end %>
              <% places_used = array.inject(0){|sum, pl| sum + pl } %>
              <%= lift.places_available - places_used %>
            </div>

            <div class="lists_header" id="contact_header">
              <%= lift.contact %>
            </div>

            <div class="lists_header" id="ticking_box_valid">
              <%= link_to "#{lift.first_name}!", lift_path(lift) %>
            </div>
          </div>
        <% end %>
        <div class="btn-lift-new">
          <%= link_to "Back", pages_path %>
        </div>
      </div>
    </div>

  <% else %>
    <div class="list-cont">
      <div class="full_title_lift">
        <div class="lift_title effect3d">
          <strong>NOS SUPER-MARIOS!  🍄 🌟</strong>
        </div>
        <div class="lift_subtitle">
          <small>Lequel de nos Super-Mario es-tu?</small>
        </div>
      </div>
      <div class="table_cont">
        <div class="lift_table">
          <div class="lists_header" id="name_header">
            <strong>NOM</strong>
          </div>

          <div class="lists_header" id="rallying_header">
            <strong>POINT DE RALLIEMENT</strong>
          </div>

          <div class="lists_header" id="departure_header">
            <strong>HEURE DE<br>DÉPART</strong>
          </div>

          <div class="lists_header" id="return_header">
            <strong>HEURE DE<br>RETOUR</strong>
          </div>

          <div class="lists_header" id="places_header">
            <strong>PLACES<br>LIBRES</strong>
          </div>

          <div class="lists_header" id="contact_header">
            <strong>CONTACT</strong>
          </div>

          <div class="lists_header" id="ticking_box_header">
            <strong>LEQUEL ES-TU?</strong>
          </div>
        </div>

        <% @lifts.each do |lift| %>
          <div class="lift_table">
            <div class="lists_header" id="name_header">
              <%= lift.first_name %> <%= lift.family_name %>
            </div>

            <div class="lists_header" id="rallying_header">
              <%= lift.rallying_point %>
            </div>

            <div class="lists_header" id="departure_header">
              <%= lift.departure.strftime('%H:%M') %>
            </div>

            <div class="lists_header" id="return_header">
              <% if lift.return.nil? %>
                N/A
              <% else %>
                <%= lift.return.strftime('%H:%M') %>
              <% end %>
            </div>

            <div class="lists_header" id="places_header">
              <% array = [0] %>
                <% lift.passengers.each do |passenger| %>
                  <% array << passenger.places %>
                <% end %>
              <% places_used = array.inject(0){|sum, pl| sum + pl } %>
              <%= lift.places_available - places_used %>
            </div>

            <div class="lists_header" id="contact_header">
              <%= lift.contact %>
            </div>

            <div class="lists_header" id="ticking_box_valid">
              <%= link_to "#{lift.first_name}!", lift_path(lift) %>
            </div>
          </div>
        <% end %>
      <div class="btn-lift-new">
        <%= link_to "Back", pages_path %>
      </div>
      </div>
    </div>
  <% end %>

</div>
<%= render 'shared/footer' %>

app/views/lifts/show.html.erb
<div class="passenger-cont">
  <div class="passenger-bg">
    <%= cl_image_tag("nrkgbrxhvbqobstcrw64") %>
  </div>
  <div class="passenger-view">
    <div class="full_title_lift">
      <div class="lift_title effect3d">
        <strong>Voici la page d'info de <%= @lift.first_name %>!</strong>
      </div>
      <br>
      <div class="lift_subtitle">
        Il y a actuellement <strong><%= @lift.passengers.count %></strong> passager(s) avec <%= @lift.first_name %> pour le grand soir!
      </div>
    </div>
    <div class="passenger-show">
      <% @lift.passengers.each do |passenger|  %>
        <div class="passenger-card">
          <div class="passenger-name">
            <h4><u><strong><em><%= passenger.first_name %> <%= passenger.family_name %></em></strong></u></h4>
          </div>

          <div class="passenger-contact">
            Contact: <u><%= passenger.contact %></u>
          </div>

          <div class="passenger-places">
            Ce passager prendra: <strong><em><%= passenger.places %> place(s)</em></strong>
          </div>

          <div class="passenger-trip">
            <div class="trip-check">
              Aller:
              <% if passenger.aller == true %>
                <div class="trip-checked"><span></span></div>
              <% else %>
                <div class="trip-not-checked"><span></span></div>
              <% end %>
            </div>

            <div class="trip-check">
              Retour:
              <% if passenger.retour == true %>
                <div class="trip-checked"><span></span></div>
              <% else %>
                <div class="trip-not-checked"><span></span></div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="btn-lift-new" id="btn-passenger">
      <%= link_to "Back", lift_index_path %>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<div class="footer-cont">
  <div class="footer">
    Copyright © 2020 István Lázár & Gauthier Wolters <br>
    All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-northern-lights">
    <ul class="navbar-links">
      <li class="navbar-item">
        <%= link_to "Accueil", accueil_index_path %>
      </li>
      <li class="navbar-item">
        <%= link_to "Répondre",  new_reponse_path %>
      </li>
      <li class="navbar-item">
        <%= link_to "Lifts", pages_path %>
      </li>
      <li class="navbar-item">
        <%= link_to "Dress Code", dress_code_index_path %>
      </li>
      <li class="navbar-item">
        <%= link_to "Photos", photos_path %>
      </li>
      <li class="navbar-item">
        <%= link_to "Remerciements", new_remerciement_path %>
      </li>
    </ul>
  <div class="logo"><%= link_to "Northern Lights", accueil_index_path %></div>
  <div class="burger">
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="line3"></div>
  </div>

</div>